### ISSUE TITLE
LysonLED P3 indoor 64x64 1/16 HUB75 panel not displaying anything until I choose outdoor then change it back.

### ISSUE THREAD

**Issue by Digital-Ark** [MoonModules/WLED#233]
### What happened?

Huidu HD-WF2 flashed with WLEDMM_14.5.0-beta_esp32S3_4MB_S.bin

On power up, nothing shows on the display, until I go into Config>LED Preferences, change it to any outdoor HUB75 module, reboot, then change it back to an indoor HUB75, then it works fine.  I can change anything, reboot, it all works until I power it off.

Then it starts-up, the web interface is available, rebooting does nothing, but if I change it again to outdoor, reboot then back to indoor, it works fine again.

Any ideas?

### To Reproduce Bug

Power off the HD-WF2.

### Expected Behavior

After setting the correct panel type, the screen should turn on when I power-up the HD-WF2.

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

WLEDMM_14.5.0-beta_esp32S3_4MB_S.bin

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Relevant log/trace output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Digital-Ark** [comment]
I bet this is it.  My panel uses FM6126A chips.

examples/FM6126Panel/FM6126Panel.ino

**Comment by Digital-Ark** [comment]
In case this helps anyone, here is the revised ESPHome yaml for a chain of 2 64x32 HUB75 panels using these FM6126A chips:

```
#
# led-matrix-hub75-huidu-wf2.yaml -- ESPhome config for the HUIDU HD-WF2 LED matrix controller
#
# (C) 2023 Hajo Noerenberg
#
# Usage: See https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/issues/433
#
# http://www.noerenberg.de/
# https://github.com/hn/esphome-configs
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.0 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
#

esphome:
  name: led-matrix-hub75-huidu-wf2
  friendly_name: LED matrix Huidu HD-WF2
  platformio_options:
    board_build.flash_mode: dio

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HD-WF2 Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

i2c:
  sda: 41
  scl: 42

time:
  - platform: pcf8563
    address: 0x51
    id: pcf8563_time
  - platform: homeassistant
    on_time_sync:
      then:
        pcf8563.write_time:

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 12

display:
  - platform: hub75_matrix_display
    id: huidu_wf2_x1
    driver: FM6126A
    i2sspeed: HZ_10M
    latch_blanking: 1
    width: 64
    height: 32
    chain_length: 2
    clock_phase: false
    R1_pin: 2
    R2_pin: 3
    G1_pin: 6
    G2_pin: 7
    B1_pin: 10
    B2_pin: 11
    A_pin: 39
    B_pin: 38
    C_pin: 37
    D_pin: 36
    E_pin: 21
    OE_pin: 35
    CLK_pin: 34
    LAT_pin: 33
    lambda: |-
      auto red = Color(255, 0, 0);
      auto blue = Color(0, 0, 255);
      auto rtc = id(pcf8563_time).now();
      it.line(4, 25, 4 + 2 * rtc.second, 25, blue);
      it.rectangle(2, 2, 124, 28, red);
      it.strftime(7, 8, id(roboto), "%Y-%m-%d %H:%M:%S", rtc);
      //it.print(20, 10, id(roboto), "Hello World!");

switch:
  - platform: hub75_matrix_display
    matrix_id: huidu_wf2_x1
    restore_mode: ALWAYS_ON
    id: matrix_power
  - platform: gpio
    id: led_run
    pin: 40

binary_sensor:
  - platform: gpio
    id: test_key
    pin:
      number: 17
      inverted: true

number:
  - platform: hub75_matrix_display
    matrix_id: huidu_wf2_x1
    name: "Brightness"
```
