### ISSUE TITLE
Maximum current and 2D configuration are reset on power cycle

### ISSUE THREAD

**Issue by stiw47** [MoonModules/WLED#33]
### What happened?

I set up max current to 4500mA for my use case.
My LED matrix is 16x16, so this is also the setup in my 2D configuration.

After each power cycle, I can find that max current is changed to 5000mA and setup in my 2D configuration is changed to 8x8.
I didn't noticed so far that anything else is messing except above 2 things.

Firstly I mean, maybe is problem with me, cause I mess a lot with different presets, so maybe it pulling these values who knows where from, but I also tried with factory reset => fresh installation and basic manual config for 16x16. However, I'm still not sure is it ESP32 keep something even after factory reset, so I would be graceful if someone could try to reproduce this. Below video explains more than my post. Issue is recorded in (atm) last commit 500, but I noticed it before in 476 (maybe even before that), but I was lazy to sit here and type 😁

https://cloud.stiw47.cloud/s/wTATwEGP52Ny28y

### To Reproduce Bug

Power cycle LED matrix => check max current and 2D layout => compare it with previous values.

### Expected Behavior

It should keep settings between power cycles 😁

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

Change library for ArtiFX 500

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
Unfortunately, I haven't it. Never catch a log for WLED before, I heard it is not that simple. On the other hand, I saw on MM repo there are some binaries with _debug in the file name, so if log is necessary, I can try.
```

### Anything else?

Thanks for great software.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stiw47** [comment]
If someone else is experiencing such an issue, I'm work around'ing it with Home Assistant automation as for now:

```
- id: '1681036996891'
  alias: King Matrix Restore Conf
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_kids_2
    to: 'on'
  condition: []
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - light.king_matrix
      to: 'on'
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: rest_command.king_matrix_restore_conf
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: button.press
    data: {}
    target:
      entity_id: button.king_matrix_restart
  mode: single
- id: '1681037968114'
  alias: Light Switch Kids 2 Off King Matrix Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_kids_2
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.king_matrix
  mode: single
```

Rest command:

```
king_matrix_restore_conf:
  url: "http://192.168.0.188/json/cfg"
  method: POST
  content_type: "application/json"
  payload: '{"rev":[1,0],"vid":2304080,"id":{"mdns":"king-matrix","name":"King Matrix","inv":"Light"},"nw":{"ins":[{"ssid":"Please wait void...","pskl":19,"ip":[0,0,0,0],"gw":[0,0,0,0],"sn":[255,255,255,0]}]},"ap":{"ssid":"WLED-AP King Matrix","pskl":8,"chan":1,"hide":0,"behav":0,"ip":[4,3,2,1]},"wifi":{"sleep":false},"hw":{"led":{"total":256,"maxpwr":4500,"ledma":55,"cct":false,"cr":false,"cb":0,"fps":42,"rgbwm":255,"ld":false,"matrix":{"mpc":1,"ba":true,"mph":1,"mpv":1,"pb":false,"pr":false,"pv":false,"ps":false,"panels":[{"b":false,"r":false,"v":false,"s":true,"x":0,"y":0,"h":16,"w":16}]},"ins":[{"start":0,"len":256,"pin":[4],"order":0,"rev":false,"skip":0,"type":22,"ref":false,"rgbwm":0}]},"com":[],"btn":{"max":4,"pull":true,"ins":[{"type":0,"pin":[-1],"macros":[0,0,0]},{"type":0,"pin":[-1],"macros":[0,0,0]},{"type":0,"pin":[-1],"macros":[0,0,0]},{"type":0,"pin":[-1],"macros":[0,0,0]}],"tt":32,"mqtt":false},"ir":{"pin":-1,"type":0,"sel":true},"relay":{"pin":-1,"rev":false},"baud":1152,"if":{"i2c-pin":[-1,-1],"spi-pin":[-1,-1,-1]}},"light":{"scale-bri":100,"pal-mode":0,"aseg":false,"gc":{"bri":1,"col":2.8,"val":2.8},"tr":{"mode":true,"dur":7,"pal":0,"rpc":5},"nl":{"mode":1,"dur":60,"tbri":0,"macro":0}},"def":{"ps":16,"on":true,"bri":255},"if":{"sync":{"port0":21324,"port1":65506,"recv":{"bri":true,"col":true,"fx":true,"grp":1,"seg":false,"sb":false},"send":{"dir":false,"btn":false,"va":false,"hue":true,"macro":false,"grp":1,"ret":0}},"nodes":{"list":true,"bcast":true},"live":{"en":true,"mso":false,"port":5568,"mc":false,"dmx":{"uni":1,"seqskip":false,"e131prio":0,"addr":1,"dss":0,"mode":4},"timeout":25,"maxbri":false,"no-gc":true,"offset":0},"va":{"alexa":false,"macros":[0,0],"p":0},"mqtt":{"en":false,"broker":"","port":1883,"user":"","pskl":0,"cid":"WLED-5155f4","topics":{"device":"wled/5155f4","group":"wled/all"}},"hue":{"en":false,"id":1,"iv":25,"recv":{"on":true,"bri":true,"col":true},"ip":[192,168,0,0]},"ndb":{"ip":[0,0,0,0],"port":1768,"enabled":false},"ntp":{"en":false,"host":"0.wled.pool.ntp.org","tz":2,"offset":0,"ampm":false,"ln":0,"lt":0}},"ol":{"clock":0,"cntdwn":false,"min":0,"max":29,"o12pix":0,"o5m":false,"osec":false},"timers":{"cntdwn":{"goal":[20,1,1,0,0,0],"macro":0},"ins":[{"en":1,"hour":255,"min":0,"macro":0,"dow":127},{"en":1,"hour":255,"min":0,"macro":0,"dow":127}]},"ota":{"lock":false,"lock-wifi":false,"pskl":7,"aota":true},"um":{"Temperature":{"enabled":false,"pin":18,"degC":true,"read-interval-s":60,"parasite-pwr":false,"parasite-pwr-pin":-1},"4LineDisplay":{"enabled":false,"pin":[-1,-1,-1,-1,-1],"type":1,"flip":false,"contrast":10,"contrastFix":false,"screenTimeOutSec":60,"sleepMode":true,"clockMode":false,"showSeconds":true,"i2c-freq-kHz":400},"Rotary-Encoder":{"enabled":false,"DT-pin":-1,"CLK-pin":-1,"SW-pin":-1,"preset-low":0,"preset-high":0,"apply-2-all-seg":true},"Autosave":{"enabled":false,"autoSaveAfterSec":15,"autoSavePreset":250,"autoSaveApplyOnBoot":false},"AudioReactive":{"enabled":false,"analogmic":{"pin":-1},"digitalmic":{"type":1,"pin":[32,15,14,-1,-1,-1]},"config":{"squelch":10,"gain":60,"AGC":1},"experiments":{"micLev":0,"freqDist":0,"freqRMS":1},"dynamics":{"limiter":true,"rise":50,"fall":300},"frequency":{"scale":3,"profile":0},"sync":{"port":11988,"mode":0}},"Weather":{"enabled":false,"apiKey":"","units":1,"minTemp":0,"maxTemp":40},"mpu6050-IMU":{"enabled":false}}}'

```
